# Generated by Django 5.1.7 on 2025-04-01 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='description',
            new_name='descripción',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='title',
            new_name='titulo',
        ),
    ]
