# Generated by Django 5.2 on 2025-04-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0002_rename_description_evento_descripción_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
