# Generated by Django 5.2 on 2025-04-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eventos", "0004_evento_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="imagenes/"),
        ),
    ]
