# Generated by Django 5.2 on 2025-04-30 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Eventos", "0006_perfil"),
    ]

    operations = [
        migrations.RenameField(
            model_name="perfil",
            old_name="imagen_perfil",
            new_name="profile_picture",
        ),
    ]
