# Generated by Django 5.2 on 2025-04-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eventos", "0007_rename_imagen_perfil_perfil_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfil",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="perfil",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="perfiles/"),
        ),
    ]
